bird_project/birdBlog/birdBlog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
# from blog import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bird_project/birdBlog/blog/urls.py
from django.urls import path, re_path
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('search/', views.SearchPageView.as_view(), name='search'),
    path('search_results/', views.SearchResultsView.as_view(), name='search_results'),
    re_path(r'^version_detail/(?P<pk>\d+)/$', views.VersionDetailView.as_view(), name="version_detail"),
]

bird_project/birdBlog/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'birdBlog/css/master.css' %}">

  </head>
  <body>

    <div id="navigation">
      <div class="box box1"><a href="{% url 'blog:home' %}">The Charlie Parker Database</a></div>
        <div class="box box2"><a href="{% url 'admin:index' %}">Admin</a></div>
        <div class="box box3"><a href="{% url 'blog:search' %}">Search</a></div>
    </div>
    <div id="gridFive">
      <div class="myContainer">
        {% block content %}
        {% endblock %}
      </div>
    </div>

    <div id="myFooter">
      &copy 2021 Jonathan Meyer <br>
      joncwmeyer@gmail.com
    </div>
  </body>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</html>

bird_project/birdBlog/templates/home.html
{% extends "base.html" %}

{% block content %}

<p>
<div class="myContainer">
  <center>Welcome to the Charlie Parker Database.</center><br>

</div>
{% endblock %}