bird_project/birdBlog/birdBlog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
# from blog import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bird_project/birdBlog/blog/urls.py
from django.urls import path, re_path
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('search/', views.SearchPageView.as_view(), name='search'),
    path('search_results/', views.SearchResultsView.as_view(), name='search_results'),
    re_path(r'^version_detail/(?P<pk>\d+)/$', views.VersionDetailView.as_view(), name="version_detail"),
]

bird_project/birdBlog/blog/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime

class Key(models.Model):
    key = models.CharField(max_length=15)
    # keys = [
    #     'Ab Major', 'A Major', 'Bb Major', 'B Major', 'C Major', 'Db Major', 'D Major', 'Eb Major', 'E Major', 'F Major', 'Gb Major', 'G Major',
    #     'A Minor', 'Bb Minor', 'B Minor', 'C Minor', 'C# Minor', 'D Minor', 'Eb Minor', 'E Minor', 'F Minor', 'F# Minor', 'G Minor', 'G# Minor'
    # ]

    def __str__(self):
        return self.key
#
class Session(models.Model):
    # %Y-%M-%D
    title = models.CharField(max_length=255)
    date = models.CharField(max_length=255, blank=True)
    # date = models.DateField(blank=True)
    location = models.TextField(blank=True)
    personnel = models.TextField(blank=True)
    # album_release = models.ForeignKey(Album, on_delete=models.CASCADE)
    album_releases = models.TextField(blank=True)

    def __str__(self):
        return f"{self.title} - {self.date}"

    def get_absolute_url(self):
        return reverse('blog:list_session')

class SongForm(models.Model):
    song_form = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.song_form

    def get_absolute_url(self):
        return reverse('blog:list_songform')

class Song(models.Model):
    title = models.CharField(max_length=255, unique=True)
    song_form = models.ForeignKey(SongForm, on_delete=models.PROTECT)
    key = models.ForeignKey(Key, on_delete=models.PROTECT)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:list_song')
#
# class Album(models.Model):
#     title = models.TextField()
#     release_date = models.DateField()

class Version(models.Model): # New version
    song = models.ForeignKey(Song, on_delete=models.PROTECT, blank=True, null=True)
    session = models.ForeignKey(Session, on_delete=models.PROTECT)
    session_song_number = models.CharField(max_length=255, blank=True, null=True)
    releases = models.CharField(max_length=2000, default="")
    version_title = models.CharField(max_length=255)
    notes = models.TextField(blank=True)
    transcription_pdf = models.FileField(upload_to='transcriptions_pdf', blank=True)
    sibelius_file = models.FileField(upload_to='sibelius_files', blank=True)
    sound_file = models.FileField(upload_to='sound_files', blank=True)
    youtube_link = models.URLField(blank=True)
    # midi_file = models.URLField(blank=True)
    # where to buy
    # could send profits to charlie parker estate

    def __str__(self):
        return f"{self.version_title} | Date: {self.session.date}"

    def get_absolute_url(self):
        return reverse('blog:list_version')


# class Version(models.Model): # old version
#     song = models.ForeignKey(Song, on_delete=models.PROTECT)
#     session = models.ForeignKey(Session, on_delete=models.PROTECT)
#     version_title = models.CharField(max_length=255)
#     notes = models.TextField(blank=True)
#     transcription_pdf = models.FileField(upload_to='transcriptions_pdf', blank=True)
#     sibelius_file = models.FileField(upload_to='sibelius_files', blank=True)
#     youtube_link = models.URLField(blank=True)
#     # midi_file = models.URLField(blank=True)
#     # where to buy
#     # could send profits to charlie parker estate
#
#     def __str__(self):
#         return f"Version: {self.version_title} Date: {self.session}"
#
#     def get_absolute_url(self):
#         return reverse('blog:list_version')

# -----------------------------------------------------------------------
# class Track(models.Model):
#     title = models.ForeignKey(required=True, on_delete=models.CASCADE)
#     song_form = models.ForeignKey(on_delete=models.CASCADE)
#     key_signature = models.ForeignKey(on_delete=models.CASCADE)
#     location = models.CharField(max_length=200)
#     date = models.DateField(required=True) # python datetime.date
#     # duration = models.DurationField()
#     personnel = models.TextArea()
#     tempo_choices = [
#         ("b", "Ballad"),
#         ("m", "Medium"),
#         ("mu", "Medium Up"),
#         ("u", "Up"),
#         ("f", "Fast"),
#     ]
#     tempo = models.CharField(max_length=2, choices=tempo_choices, default="Medium")
#     transcription_upload = models.FileField(upload_to='transcriptions/') # file will be uploaded to MEDIA_ROOT/uploads
#
#     def get_absolute_url(self):
#         # once done creating post (after hitting publication)
#         # go to post_detail, using primary key of post just created
#         return reverse("post_detail",kwargs={'pk':self.pk})
#
#     def __str__(self):
#         return self.title, self.date
#
#
# from django.db import models
# from django.utils import timezone
# from django.urls import reverse
#
# # Create your models here.
# class Post(models.Model):
#     author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
#     title = models.CharField(max_length=200)
#     text = models.TextField()
#     create_date = models.DateTimeField(default=timezone.now)
#     published_date = models.DateTimeField(blank=True,null=True)
#
#     def publish(self):
#         self.published_date = timezone.now()
#         self.save()
#
#     def approve_comments(self):
#         return self.comments.filter(approved_comment=True)
#
#     def get_absolute_url(self):
#         # once done creating post (after hitting publication)
#         # go to post_detail, using primary key of post just created
#         return reverse("post_detail",kwargs={'pk':self.pk})
#
#     def __str__(self):
#         return self.title

bird_project/birdBlog/blog/forms.py
from django import forms
from . import models

# using django-search-views API
# class VersionSearchForm(forms.Form):
#     search_personnel = forms.CharField(required=False, label='Search Keyword', widget=forms.TextInput(attrs={'placeholder': 'search here!'}))


# class SessionModelForm(ModelForm):
#     date = DateField(widget=DateInput
#         (attrs={'placeholder':'yyyy-mm-dd'})
#     )
#     class Meta:
#         model = models.Session
#         fields = ['title', 'date', 'location', 'personnel', 'album_releases']
#
# class SongFormModelForm(ModelForm):
#     class Meta:
#         model = models.SongForm
#         fields = ['song_form']
#
# class SongModelForm(ModelForm):
#     class Meta:
#         model = models.Song
#         fields = ['title', 'song_form', 'key']
#
# class VersionModelForm(ModelForm):
#     class Meta:
#         model = models.Version
#         fields = ['song', 'session', 'version_title', 'notes', 'transcription_pdf', 'sibelius_file', 'youtube_link']


# class TrackForm(ModelForm):
#     class Meta:
#         model = models.Track
#         fields = ['song_name','title', 'recording_date', 'personnel', 'notes']
#
#         # widgets = {
#         #     'recording_date': DateInput
#         # }
#     #     widgets = {
#     #         'personnel': Textarea(attrs={'class':'editable'}),
#     #         'notes': Textarea(attrs={'class':'editable'})
#     #     }
#     # def __init__(self, *args, **kwargs):
#     #     super().__init__(*args,**kwargs)
#     #     self.fields['song_name'].label = 'Song Name'
#     #     self.fields['title'].label = "Specific Track Name"

bird_project/birdBlog/blog/views.py
from django.db.models import Q
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse
from . import forms
from . import models


class HomePageView(generic.TemplateView):
    template_name = "home.html"

class SearchPageView(generic.TemplateView):
    template_name = "blog/search.html"
    keys = [
        "" , 'Ab Major', 'A Major', 'Bb Major', 'B Major', 'C Major', 'Db Major', 'D Major', 'Eb Major', 'E Major', 'F Major', 'Gb Major', 'G Major',
        'A Minor', 'Bb Minor', 'B Minor', 'C Minor', 'C# Minor', 'D Minor', 'Eb Minor', 'E Minor', 'F Minor', 'F# Minor', 'G Minor', 'G# Minor'
    ]
    def get_context_data(self, **kwargs):
        context = super(SearchPageView, self).get_context_data(**kwargs)
        context.update({'keys': self.keys})
        return context

class SearchResultsView(generic.ListView):
    model = models.Version
    template_name = 'blog/search_results.html'

    def get_queryset(self):
        object_list = models.Version.objects.all()

        key_query = self.request.GET.get('key')
        if key_query:
            object_list = object_list.filter(song__key__key__icontains=key_query)
             # object_list = models.Version.objects.raw("SELECT * FROM blog_version")

        form_query = self.request.GET.get('form')
        if form_query:
            object_list = object_list.filter(song__song_form__song_form__icontains=form_query)

        form_query = self.request.GET.get('song')
        if form_query:
            object_list = object_list.filter(version_title__icontains=form_query)

        form_query = self.request.GET.get('person')
        if form_query:
            queries = form_query.split(", ")
            for query in queries:
                object_list = object_list.filter(session__personnel__icontains=query)

        form_query = self.request.GET.get('date')
        if form_query:
            object_list = object_list.filter(session__date__icontains=form_query)

        form_query = self.request.GET.get('location')
        if form_query:
            object_list = object_list.filter(session__location__icontains=form_query)

        form_query = self.request.GET.get('album')
        if form_query:
            object_list = object_list.filter(session__album_releases__icontains=form_query)

        form_query = self.request.GET.get('notes')
        if form_query:
            object_list = object_list.exlude(notes__icontains=form_query)

        form_query = self.request.GET.get('pdf')
        if form_query:
            object_list = object_list.exclude(transcription_pdf="")

        form_query = self.request.GET.get('sound')
        if form_query:
            object_list = object_list.exclude(sound_file="")

        form_query = self.request.GET.get('youtube')
        if form_query:
            object_list = object_list.exclude(youtube_link="")

        # person_query = self.request.GET.get('person')
        # object_list = models.Version.objects.filter(session__personnel__icontains=person_query)
        return object_list

class VersionDetailView(generic.DetailView):
    model = models.Version
    template_name = 'blog/version_detail.html'

    def get_object(self, queryset=None):
        return models.Version.objects.get(pk=self.kwargs.get("pk"))

class VersionListView(generic.ListView):
    model = models.Version

bird_project/birdBlog/blog/templates/blog/all_version_list.html
{% extends "blog/blog_base.html" %}

{% block content %}
  {% for version in version_list %}
    <table>
      <th colspan="2">{{ version.version_title }}</th>
      <tr>
        <td>Song</td>
        <td>{{ version.song }}</td>
      </tr>
      <tr>
        <td>Date</td>
        <td>{{ version.session.date }}</td>
      </tr>
      {% if version.notes %}
      <tr>
        <td>Notes</td>
        <td>{{ version.notes }}</td>
      </tr>
      {% endif %}
      {% if version.transcription_pdf %}
        <tr>
          <td>Transcription .pdf</td>
          <td><a href="{{ version.transcription_pdf.url }}" target="_blank">View PDF</a></td>
        </tr>
      {% endif %}
      {% if version.sibelius_file %}
        <tr>
          <td>Transcription .sib</td>
          <td><a href="{{ version.sibelius_file.url }}" download>Download sibelius file</a></td>
        </tr>
      {% endif %}
      {% if version.youtube_link %}
      <tr>
        <td>YouTube</td>
        <td><a href="{{ version.youtube_link }}" target='_blank'>{{ version.youtube_link }}</a></td>
      </tr>
      {% endif %}
    </table><br>
  {% endfor %}
{% endblock %}

bird_project/birdBlog/blog/templates/blog/blog_base.html
{% extends "base.html" %}

{% block content %}
{% endblock %}

bird_project/birdBlog/blog/templates/blog/search.html
{% extends "blog/blog_base.html" %}

{% block content %}

<h1>Use one or multiple filters to narrow your search</h1>
<form class="" action="{% url 'blog:search_results' %}" method="GET">
  {% csrf_token %}
  <label for="key">Key</label>
  <!-- <input name="key" type="text" name="" id="key" placeholder="Search..."> -->
  <select name="key">
    <!-- <% keys = [
        'Ab Major', 'A Major', 'Bb Major', 'B Major', 'C Major', 'Db Major', 'D Major', 'Eb Major', 'E Major', 'F Major', 'Gb Major', 'G Major',
        'A Minor', 'Bb Minor', 'B Minor', 'C Minor', 'C# Minor', 'D Minor', 'Eb Minor', 'E Minor', 'F Minor', 'F# Minor', 'G Minor', 'G# Minor'
    ] %> -->
    {% for k in keys %}
      <option>{{k}}</option>
    {% endfor %}

  </select>

  <label for="form">Song Form</label>
  <input name="form" type="text" name="" id="form" placeholder="Song form...">

  <label for="song">Song</label>
  <input name="song" type="text" name="" id="song" placeholder="Song...">

  <label for="person">Personnel (Seperate by commas if you want to search for multiple persons together)</label>
  <input name="person" type="text" name="" id="person" placeholder="Personnel...">

  <label for="date">Date</label>
  <input name="date" type="text" name="" id="date" placeholder="Date...">

  <label for="location">Location</label>
  <input name="location" type="text" name="" id="location" placeholder="Album...">

  <label for="album">Album</label>
  <input name="album" type="text" name="" id="album" placeholder="Album...">

  {% if user.is_superuser or user.is_staff %}

    <label for="notes">Notes</label>
    <input name="notes" type="text" name="" id="notes" placeholder="Date...">

    <label for="pdf">PDF Download Availabe</label>
    <input class="checkmark" name="pdf" id="pdf" type="checkbox"><br>

    <label for="sound">Sound File Download Available</label>
    <input class="checkmark" name="sound" id="sound" type="checkbox"><br>

  {% endif %}

  <label for="youtube">YouTube Link Available</label>
  <input class="checkmark" name="youtube" id="youtube" type="checkbox"><br>

  <input type="submit" name="" value="SEARCH">
</form>

{% endblock %}

bird_project/birdBlog/blog/templates/blog/search_results.html
{% extends "blog/blog_base.html"%}

{% block content %}

<h1 class="myHeaders">Search Results</h1>

<table>
  {% for obj in object_list %}
  <tr>
  <td>
    <a href="{% url 'blog:version_detail' pk=obj.pk %}">{{obj.version_title}}</a>
  </td>
  <td>
    {{obj.session}}
  </td>
  </tr>
  {% endfor %}
</table>

<div class="counter">
  {{ object_list.count }} matches
</div>

{% endblock %}

bird_project/birdBlog/blog/templates/blog/version_detail.html
{% extends "blog/blog_base.html" %}

{% block content %}
  <table>
    <th colspan="2">{{ object.version_title }}</th>
    {% if object.song %}
      <tr>
        <td>Song</td>
        <td>{{ object.song }}</td>
      </tr>
      <tr>
        <td>Song Form</td>
        <td>{{ object.song.song_form }}</td>
      </tr>
    {% endif %}
    <tr>
      <td>Date</td>
      <td>{{ object.session.date }}</td>
    </tr>
    <tr>
      <td>Location</td>
      <td>{{ object.session.location }}</td>
    </tr>
    <tr>
      <td>Personnel</td>
      <td>{{ object.session.personnel }}</td>
    </tr>
    <tr>
      <td>Session</td>
      <td>{{ object.session }}</td>
    </tr>

    {% if user.is_superuser or user.is_staff %}
      {% if object.notes %}
      <tr>
        <td>Notes</td>
        <td>{{ object.notes }}</td>
      </tr>
      {% endif %}
      {% if object.transcription_pdf %}
        <tr>
          <td>Transcription .pdf</td>
          <td><a href="{{ object.transcription_pdf.url }}" target="_blank">View PDF</a></td>
        </tr>
      {% endif %}
      {% if object.sibelius_file %}
        <tr>
          <td>Transcription .sib</td>
          <td><a href="{{ object.sibelius_file.url }}" download>Download Sibeleius File</a></td>
        </tr>
      {% endif %}
      {% if object.sound_file %}
        <tr>
          <td>Sound File</td>
          <td><a href="{{ object.sound_file.url }}" download>Download Sound File</a></td>
        </tr>
      {% endif %}
    {% endif %}

    {% if object.youtube_link %}
    <tr>
      <td>YouTube</td>
      <td><a href="{{ object.youtube_link }}" target='_blank'>{{ object.youtube_link }}</a></td>
    </tr>
    {% endif %}
    <tr>
      <td>Track Releases</td>
      <td>{{ object.releases }}</td>
    </tr>
    <tr>
      <td>Album Releases</td>
      <td>
        {{ object.session.album_releases }}
    </tr>
  </table><br>
{% endblock %}